### ISSUE TITLE
한국어 생성 성능 문의

### ISSUE THREAD

**Issue by yunsangju** [kakaobrain/honeybee#10]
안녕하세요.
https://www.hani.co.kr/arti/economy/it/1125130.html 해당 기사를 보면 허니비가 한국어도 잘 생성하는 것처럼 보이는데요.
모델 checkpoint를 받아서 generate해보니 영어로 생성합니다.
모델 구조를 보면 vicuna에 사용한 학습데이터도 영어만 있던 것같은데요.
해당 기사가 기자가 번역해서 홍보한건지 아니면 한국어를 잘 생성하는 별도의 모델이 있는지 문의드립니다.

**Comment by khanrc** [comment]
First of all, thank you for your interest in our research. As this page is globally accessible, I will respond in English. If you prefer communicating in Korean, feel free to reach out via email (logan.cha@kakaobrain.com) :)

The image in the article seems to be a Korean translation of an English response from Honeybee. We did not use a Korean-specialized model for the article.
