### ISSUE TITLE
About the pre-training checkpoints

### ISSUE THREAD

**Issue by yuxie11** [kakaobrain/honeybee#13]
Hi, 
thanks for your nice work! Can you share the pre-training checkpoints after the first stage?

**Comment by poisonwine** [comment]
> Hi, thanks for your nice work! Can you share the pre-training checkpoints after the first stage?

the same question

**Comment by khanrc** [comment]
Thank you for your interest in our work! We will share the pre-training checkpoints soon, with training codes.

**Comment by wykang** [comment]
@yuxie11 @poisonwine We are happy to inform you that our pre-training checkpoints were released yesterday. You can download and use them right now :).
