### ISSUE TITLE
Hello, I have a question. Is it possible to disclose the code for the training process?

### ISSUE THREAD

**Issue by leedaehan-kev** [kakaobrain/honeybee#15]
First of all, I would like to express my astonishment at the incredible multi-modal research created by Kakao. It's fascinating and surprising to witness such developments in Korea, thanks to Kakao's efforts in building this model.

My question is as follows: When do you plan to release the training code, including training tracing like with Wandb? It would be great if you could provide a specific date or at least a general time frame.

Thank you.

**Comment by wykang** [comment]
Thank you very much for expressing interest in our research. We are currently working on releasing the training code, and we anticipate it will be available by this month or, at the latest, within the next month.
