### ISSUE TITLE
Question abut think token

### ISSUE THREAD

**Issue by Yi-Qi638** [kakaobrain/honeybee#17]
Hi~
There is eos token when build C-Abstractor
> def build_eos_tokens(config: HoneybeeVisualProjectorConfig, output_hidden_size: int):
    # think tokens
    num_eos_tokens = config.num_eos_tokens
    if num_eos_tokens:
        eos_tokens = torch.nn.Parameter(torch.randn(1, num_eos_tokens, output_hidden_size))
        nn.init.trunc_normal_(eos_tokens, mean=0.0, std=config.initializer_range)
    else:
        eos_tokens = None
    return eos_tokens
    
   This is interesting and Is it necessary or important?

**Comment by khanrc** [comment]
We initially thought this eos tokens might be beneficial when conducting the experiments, but it turned out they weren't necessary. In fact, we found that removing this think or image indicator tokens actually improved performance. Table 10 in Appendix shows the results.
