### ISSUE TITLE
cAbstractor depth param error

### ISSUE THREAD

**Issue by shakedpe** [kakaobrain/honeybee#19]
Hi,
Within the cAbstractor class, there is a depth param defined as:
        depth = self.config.depth
The config file is from the type HoneybeeVisualProjectorConfig as can be seen within the projector class which we inherent from. However HoneybeeVisualProjectorConfig has no param of depth, and so we end up with an error.
Where is the depth param coming from if the config file doesnt have it?
Thanks

**Comment by khanrc** [comment]
Hello,
the released checkpoint includes the model config, which specifies the depth.
FYI, we used the depth of 3.
