### ISSUE TITLE
About the SFT Rec task data

### ISSUE THREAD

**Issue by AlanWang0o0** [kakaobrain/honeybee#23]
According to your paper, the REC tasks (RefCOCO, RefCOCO+, RefCOCOg, VG) in the SFT stage contain a total of 5.7 million samples. In contrast, LLaVa uses RefCOCO + VG and contains 1.2 million samples. Could you please clarify the differences between the data you used and the data used by LLaVa?

**Comment by khanrc** [comment]
5.7M indicates the size of entire dataset. In contrast, LLaVA only mentioned the number of samples they used.
Similarly, we also did not use the entire dataset. Specifically, the actual number of fine-tuning samples is 128\*10k and the total REC ratio is 0.36, thus, the total used samples of REC is 0.36\*128\*10k = 0.46M.
