### ISSUE TITLE
Data and training code

### ISSUE THREAD

**Issue by sxu1997** [kakaobrain/honeybee#6]
Hi,
Thanks your great work! When will relaese data and training code?

**Comment by khanrc** [comment]
Thank you for your interest in our work. The release date is not strictly decided yet, but we approximately plan to release it by next month.

**Comment by abrahimzaman360** [comment]
is it trained on Korean Language aswell?

**Comment by wykang** [comment]
@sxu1997 Now, we support training pipelines for our Honeybee. 
For the data, please follow the guidelines in the [Data Preparation](https://github.com/kakaobrain/honeybee?tab=readme-ov-file#data-preparation) section.

**Comment by wykang** [comment]
@abrahimzaman360 We did not use any Korean-specific datasets.
