### ISSUE TITLE
[Question] Evaluation error

### ISSUE THREAD

**Issue by caramel678** [kakaobrain/honeybee#8]
(bee) D:\honeybee-main>python -m serve.web_server --bf16 --port 8899 --base-model checkpoints/7B-C-Abs-M144/last             
 >>> Init server
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:997)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

The above exception was the direct cause of the following exception:

_______________________
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by khanrc** [comment]
It seems from the error message that there is a problem with the internet connection or it is in offline mode.

**Comment by caramel678** [comment]
Can downloading openai/clip-vit-target-patch14 solve this problem？

**Comment by caramel678** [comment]
Thank you, I will try it out.
