### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by ZoneFv** [kakaobrain/honeybee#9]
What is the amount of training data used in the stage1 and stage2?
Can you open source the data information used for training?

**Comment by khanrc** [comment]
All of the information about the data we used are included in the paper, including datasets ratio.
<img width="420" alt="image" src="https://github.com/kakaobrain/honeybee/assets/3657248/3081f956-014f-4da7-a5d0-48672174f47d">

Our final models are trained with 200k\*256 (=51M) and 10k\*128 (=1.3M) examples in pre-training and instruction tuning, respectively.

**Comment by yuxie11** [comment]
Hi, since you are using a multi-round dialog format, does 130M represent the number of images used, or the total number of dialogs?

**Comment by khanrc** [comment]
Each multi-round dialog has a single image. Hence, 1.3M (not 130M) is the number of images and dialogues (and the number of rounds > 1.3M).

**Comment by ZoneFv** [comment]
use a single node with A100 80GB × 8，with the current amount of training data， how much time did the two stages take?

**Comment by khanrc** [comment]
It depends on the model configuration. For `Honeybee-C-7B-M144` with ablation setting (50k pre-training and 4k instruction tuning), the total training time (including intermediate evaluations) is about 30.7H and 5.7H for pre-training and instruction tuning, respectively.
